### ISSUE TITLE
小鸡词典查梗，按照格式发送未识别

### ISSUE THREAD

**Issue by Bestlm** [djkcyl/ABot-Graia#21]
![image](https://user-images.githubusercontent.com/29437027/145513109-3f52e0ac-bd8f-4034-bdbe-0184b1bd97e1.png)

**Comment by djkcyl** [comment]
![image](https://user-images.githubusercontent.com/59153990/145514291-6d83a7ba-a072-4a6f-b57c-57d1d7a1ae73.png)

**Comment by djkcyl** [comment]
你的问题

**Comment by Bestlm** [comment]
重新拉取依赖解决
