### ISSUE TITLE
机器人加载出错TypeError: argument 1 must be str, not WindowsPath

### ISSUE THREAD

**Issue by tendapc** [djkcyl/ABot-Graia#25]
| ERROR    | graia.ariadne.util:loguru_excepthook:95 - Exception:
Traceback (most recent call last):

  File "D:\ABot-Graia\main.py", line 80, in <module>
    app.launch_blocking()
    │   └ <function Ariadne.launch_blocking at 0x000001E9002F09D0>
    └ <graia.ariadne.app.Ariadne object at 0x000001E9003930A0>

  File "D:\ABot-Graia\virtualenvs\abot-mahv2-k57XDBYX-py3.9\lib\site-packages\graia\ariadne\app.py", line 1428, in launch_blocking
    self.loop.run_until_complete(self.lifecycle())
    │    │    │                  │    └ <function Ariadne.lifecycle at 0x000001E9002F0940>
    │    │    │                  └ <graia.ariadne.app.Ariadne object at 0x000001E9003930A0>
    │    │    └ <function BaseEventLoop.run_until_complete at 0x000001E97F1EB8B0>
    │    └ <ProactorEventLoop running=True closed=False debug=False>
    └ <graia.ariadne.app.Ariadne object at 0x000001E9003930A0>

  File "D:\python\python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000001E97F2AA5E0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "D:\python\python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()

  File "D:\python\python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000001E97F1EF3A0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "D:\python\python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000001E97F17FF70>
    └ <Handle <TaskWakeupMethWrapper object at 0x000001E928E76670>(<Future finished result=None>)>

  File "D:\python\python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x000001E928E76670>(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskWakeupMethWrapper object at 0x000001E928E76670>(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x000001E928E76670>(<Future finished result=None>)>

> File "D:\ABot-Graia\virtualenvs\abot-mahv2-k57XDBYX-py3.9\lib\site-packages\graia\broadcast\__init__.py", line 166, in Executor
    result = await run_always_await_safely(target_callable, **parameter_compile_result)
                   │                       │                  └ {}
                   │                       └ <function cpuStatus at 0x000001E925C21AF0>
                   └ <function run_always_await_safely at 0x000001E97F8A9A60>

  File "D:\ABot-Graia\virtualenvs\abot-mahv2-k57XDBYX-py3.9\lib\site-packages\graia\broadcast\utilles.py", line 23, in run_always_await_safely
    return await callable(*args, **kwargs)
                 │         │       └ {}
                 │         └ ()
                 └ <function cpuStatus at 0x000001E925C21AF0>

  File "D:\ABot-Graia\saya\SystemStatus\__init__.py", line 46, in cpuStatus
    disk = psutil.disk_usage(Path.cwd())
           │      │          │    └ <classmethod object at 0x000001E97F2FCC10>
           │      │          └ <class 'pathlib.Path'>
           │      └ <function disk_usage at 0x000001E925C91040>
           └ <module 'psutil' from 'D:\\ABot-Graia\\virtualenvs\\abot-mahv2-k57XDBYX-py3.9\\lib\\site-packages\\psutil\\__init__.py'>

  File "D:\ABot-Graia\virtualenvs\abot-mahv2-k57XDBYX-py3.9\lib\site-packages\psutil\__init__.py", line 2003, in disk_usage
    return _psplatform.disk_usage(path)
           │           │          └ WindowsPath('D:/ABot-Graia')
           │           └ <function disk_usage at 0x000001E925C84F70>
           └ <module 'psutil._pswindows' from 'D:\\ABot-Graia\\virtualenvs\\abot-mahv2-k57XDBYX-py3.9\\lib\\site-packages\\psutil\\_pswind...

  File "D:\ABot-Graia\virtualenvs\abot-mahv2-k57XDBYX-py3.9\lib\site-packages\psutil\_pswindows.py", line 274, in disk_usage
    total, free = cext.disk_usage(path)
                  │    │          └ WindowsPath('D:/ABot-Graia')
                  │    └ <built-in function disk_usage>
                  └ <module 'psutil._psutil_windows' from 'D:\\ABot-Graia\\virtualenvs\\abot-mahv2-k57XDBYX-py3.9\\lib\\site-packages\\psutil\\_p...

TypeError: argument 1 must be str, not WindowsPath
怎么处理

**Comment by djkcyl** [comment]
请发pastebin或者使用Markdown语法

**Comment by tendapc** [comment]
https://pastebin.com/ih7VaUA9
这个吗
