### ISSUE TITLE
连不上mah

### ISSUE THREAD

**Issue by tanpan428** [djkcyl/ABot-Graia#31]
配置检查了好几遍了……死活连不上
[1.zip](https://github.com/djkcyl/ABot-Graia/files/8077285/1.zip)

**Comment by tanpan428** [comment]
2022-02-16 14:38:10.005 | CRITICAL | graia.ariadne.app:daemon:1346 - Timeout when connecting to mirai-api-http. Configuration problem?
2022-02-16 14:38:10.007 | WARNING  | graia.ariadne.app:daemon:1360 - daemon: adapter down, restart in 5.0s
2022-02-16 14:38:15.004 | INFO     | graia.ariadne.app:daemon:1362 - daemon: restarting adapter

Basic:
  API:
    Tencent:
      Cos:
        bucket: xxxxx
        region: xxxxx
      secretId: xxxxx
      secretKey: xxxxx
  BotName: bot
  CoinName: 游戏币
  Event:
    JoinGroup: true
    KickGroup: true
    LeaveGroup: true
    Mute: true
    NewFriend: true
    PermissionChange: true
  MAH:
    BotQQ: 3519993484
    MiraiAuthKey: '1234567890'
    MiraiHost: http://127.0.0.1:12345
  Permission:
    Admin:
    - 1394109284
    Debug: false
    DebugGroup: 123
    DefaultAcceptInvite: true
    Master: 1394109284
    MasterName: hZs-1
    Rest: true
Final: true
Saya:
  AnimeSceneSearch:
    Disabled: true
    saucenao_key: xxxxxxxxxxxxx
    tracemoe_key: xxxxxxxxxxxxx
  AnitRecall:
    Disabled: false
    Moderation:
      Disabled: false
  ArkGuessOperator:
    Disabled: false
  ArkNews:
    Disabled: false
  ArkRecruit:
    Disabled: false
  AzureTTS:
    Disabled: true
    Region: xxxxx
    Subscription: xxxxx
  Beast:
    BeastPhrase:
    - 嗷
    - 呜
    - 啊
    - '~'
    Disabled: false
  BilibiliDynamic:
    Disabled: false
    EnabledProxy: true
    Intervals: 30
    Proxy:
    - http://127.0.0.1:1080
  BilibiliResolve:
    Disabled: false
  Calculator:
    Disabled: false
  CharacterDesignGenerator:
    Disabled: false
  ChatMS:
    Disabled: false
  ChickDict:
    Disabled: false
  ChickEmoji:
    Disabled: false
  ChineseDict:
    Disabled: false
  CloudMusic:
    ApiConfig:
      Password: tanpan428
      PhoneNumber: 17716845991
    Disabled: false
    MusicInfo: true
  CyberBlacktalk:
    Disabled: false
  DailyNewspaper:
    Disabled: false
  DiceMaid:
    Disabled: false
  DrawSomething:
    Disabled: false
  DriftingBottle:
    Disabled: false
  EnglishTest:
    Disabled: false
  GroupConfig:
    Disabled: false
  HorseRacing:
    Disabled: true
  Lottery:
    Disabled: true
  LowPolygon:
    Disabled: false
  Message:
    Disabled: false
  MinecraftPing:
    Disabled: false
  MutePack:
    Disabled: true
    MaxJackpotProbability: 10000
    MaxMultiple: 8
    MaxSuperDoubleMultiple: 12
    MaxSuperDoubleProbability: 25
    MaxTime: 3000
    SuperDouble: true
  PetPet:
    CanAt: true
    CanNudge: true
    Disabled: false
  Pixiv:
    Disabled: false
    Forward: true
    Interval: 10
    Recall: true
    san: r18
  Real-ESRGAN:
    Disabled: false
    MaxSize: 16000000
    Review: true
    UpdateCos: false
  RecordQuery:
    Disabled: true
    r6:
      password: xxxxxxxxxxxxxx
      user_id: xxxxxxxxxxxxx
  Reminder:
    Disabled: false
  Repeater:
    Disabled: false
    Random:
      Disabled: false
      Probability: 260
    RepeatTimes: 3
  Setu:
    Disabled: false
  Sign:
    Disabled: false
  StyleLogoGenerator:
    Disabled: false
  Transfer:
    Disabled: false
  UserFunction:
    Disabled: false
  VoiceMusicRecognition:
    Disabled: true
    humming:
      access_key: xxxxx
      access_secret: xxxxx
      host: xxxxx
    original:
      access_key: xxxxx
      access_secret: xxxxx
      host: xxxxx
  WordCloud:
    Disabled: false
  Yinglish:
    Disabled: false

## 配置文件中的值，全为默认值

## 启用的 adapter, 内置有 http, ws, reverse-ws, webhook
adapters:
  - http
  - ws

## 是否开启认证流程, 若为 true 则建立连接时需要验证 verifyKey
## 建议公网连接时开启
enableVerify: true
verifyKey: 1234567890

## 开启一些调式信息
debug: true

## 是否开启单 session 模式, 若为 true，则自动创建 session 绑定 console 中登录的 bot
## 开启后，接口中任何 sessionKey 不需要传递参数
## 若 console 中有多个 bot 登录，则行为未定义
## 确保 console 中只有一个 bot 登陆时启用
singleMode: false

## 历史消息的缓存大小
## 同时，也是 http adapter 的消息队列容量
cacheSize: 4096

## adapter 的单独配置，键名与 adapters 项配置相同
adapterSettings:
  ## 详情看 http adapter 使用说明 配置
  http:
    host: 127.0.0.1
    port: 12345
    cors: ["*"]
  
  ## 详情看 websocket adapter 使用说明 配置
  ws:
    host: 127.0.0.1
    port: 12345
    reservedSyncId: -1

**Comment by djkcyl** [comment]
![}UWLYF`L2GQ_VX{(IM%PK}B](https://user-images.githubusercontent.com/59153990/154210359-77b5033a-77be-45e8-b786-4cdf5e0dfa7a.jpg)

**Comment by tanpan428** [comment]
我平常code不用md啊……
要不我qq：1394109284我把文件发给你？
万分感谢

**Comment by djkcyl** [comment]
你的mah跟 abot 是一起启动的？

**Comment by tanpan428** [comment]
对啊，先启动mah再启动abot，mah用的是mcl1.1.2，没在abot根目录，有mah插件

**Comment by djkcyl** [comment]
请再看一遍部署指南，自行查错

**Comment by tanpan428** [comment]
还是不对……我已经把两份配置重新整了一遍了

**Comment by djkcyl** [comment]
请重新检查所有所需安装的程序及依赖的版本号

**Comment by tanpan428** [comment]
没问题啊
python是3.9.9
mah是2.4
其他的都安装了的

**Comment by djkcyl** [comment]
截图完整的mirai启动后日志

**Comment by tanpan428** [comment]
![image](https://user-images.githubusercontent.com/66200546/154214425-e7b7d7d6-6051-49bb-a3d5-d53cb993deba.png)

**Comment by tanpan428** [comment]
所以这个配置有什么问题吗

**Comment by djkcyl** [comment]
![image](https://user-images.githubusercontent.com/59153990/154216956-9fc2ea6c-e793-4daf-bcc8-e3bef4bf567f.png)
![image](https://user-images.githubusercontent.com/59153990/154216989-a076bf04-f59d-4d5c-a310-becc5fe1c9d9.png)

**Comment by tanpan428** [comment]
不是，我现在已经把两边改回来改成8066了，abot的配置里现在也是8066

**Comment by djkcyl** [comment]
那就吧两边的配置文件和运行日志都截图

**Comment by tanpan428** [comment]
![image](https://user-images.githubusercontent.com/66200546/154217440-16d633b1-28e1-4a59-abea-dfb27143af50.png)
![image](https://user-images.githubusercontent.com/66200546/154217498-b90cf545-79eb-4f2b-9860-df401bb22d6f.png)
![image](https://user-images.githubusercontent.com/66200546/154217705-d6135e91-8f44-4795-b29d-91e2fa7a27d4.png)
![image](https://user-images.githubusercontent.com/66200546/154217739-2d447776-adbd-490f-8e64-a169a2013168.png)

**Comment by djkcyl** [comment]
离谱

**Comment by tanpan428** [comment]
咋了

**Comment by tanpan428** [comment]
所以怎么办……
